### PR TITLE
Using Rate-Limit Wait as sent by header

### PR DESCRIPTION
**Pull request by anshumangoyal**

### CODE REVIEW

**Comment by anshumangoyal** [comment]
@tolstislon can you please approve this pull request and merge the code. The rate limit has not been handled properly and I have added a fix for that. Let me know if you have any questions related to that and/or suggestions how I should use this.

**Comment by anshumangoyal** [comment]
I have not idea why this is failing. I reformatted the file with pyCharm, still it is failing at some reformat:
https://travis-ci.com/github/tolstislon/testrail-api/jobs/338205270

**Comment by tolstislon** [comment]
@anshumangoyal Thanks for PR

Maybe it would be better to replace with `time.sleep(int(response.headers.get("retry-after", RATE_LIMIT_TIMEOUT)))` ?

Use black https://github.com/psf/black
He probably didn’t like it `'`

**Comment by anshumangoyal** [comment]
@tolstislon done. Updated that.

**Comment by anshumangoyal** [comment]
@tolstislon can you please merge this now. I have a dependency where this is being used and want to resolve this immediately.

**Comment by anshumangoyal** [comment]
Thanks, how much time will it take for the tar ball to be available in pypi?

**Comment by tolstislon** [comment]
once https://travis-ci.com/github/tolstislon/testrail-api/builds/167526655

**Pull request merged**
